### ISSUE TITLE
[Feature Request] Mouse/Movement Tweaks

### ISSUE THREAD

**Issue by King-INF3RN0** [Johnsmith0508/cubes#11]
I'd like to request the following features to be added:
- Hide mouse
- Make it so that the mouse moves the view w/o clicking+dragging
- Changeable mouse sensitivity
- Pause (ESC) function to regain regular mouse control/bring up menu w/ possible adverts and/or contact info

**Comment by Johnsmith0508** [comment]
Personal Refernce - look into `THREE.PointerLockControls`

Also: to respond to the suggestions, I am hesitant to lock the mouse for a variety of reasons. First and foremost, I don't trust my code enough to guarantee that the mouse will be returned to the control of the user. A secondary reason is that most modern web browsers agree with my first point. For example : with chrome, it will ask permision to lock the cursor, an extra (ultimately unnecessary) step to play my game.

The mouse sensitivity is mainly a hardware option, though the `controls.rotateSpeed` variable does seem to have the intended effect. 

please comment if you have any clarifications or otherwise.
